DROP TABLE IF EXISTS netex.st_netex_admin_zone CASCADE;
DROP TABLE IF EXISTS netex.st_netex_composite_frame CASCADE;
DROP TABLE IF EXISTS netex.st_netex_general_frame CASCADE;
DROP TABLE IF EXISTS netex.st_netex_line CASCADE;
DROP TABLE IF EXISTS netex.st_netex_network CASCADE;
DROP TABLE IF EXISTS netex.st_netex_point_on_journey CASCADE;
DROP TABLE IF EXISTS netex.st_netex_point_on_route CASCADE;
DROP TABLE IF EXISTS netex.st_netex_product_category CASCADE;
DROP TABLE IF EXISTS netex.st_netex_quay CASCADE;
DROP TABLE IF EXISTS netex.st_netex_resource_frame CASCADE;
DROP TABLE IF EXISTS netex.st_netex_responsibility_set CASCADE;
DROP TABLE IF EXISTS netex.st_netex_route CASCADE;
DROP TABLE IF EXISTS netex.st_netex_scheduled_stop_point CASCADE;
DROP TABLE IF EXISTS netex.st_netex_service_frame CASCADE;
DROP TABLE IF EXISTS netex.st_netex_delivery CASCADE;
DROP TABLE IF EXISTS netex.st_netex_site_frame CASCADE;
DROP TABLE IF EXISTS netex.st_netex_stop_place CASCADE;
DROP TABLE IF EXISTS netex.st_netex_version CASCADE;
DROP SEQUENCE IF EXISTS netex.st_netex_composite_frame_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_delivery_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_general_frame_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_line_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_product_category_id_sequence;
DROP SEQUENCE IF EXISTS netex.st_netex_quay_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_resource_frame_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_responisibility_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_route_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_sch_stop_point_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_service_frame_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_site_frame_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_stop_place_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_version_id_seq;
DROP SEQUENCE IF EXISTS netex.st_netex_admin_zone_id;
DROP SEQUENCE IF EXISTS netex.st_netex_network_id;
DROP SEQUENCE IF EXISTS netex.st_netex_point_on_journey_id;
DROP SEQUENCE IF EXISTS netex.st_netex_point_on_route_id;

